list: $/pensoft/calendar/models/category/columns.yaml
modelClass: Pensoft\Calendar\Models\Category
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/calendar/categories/update/:id'
