title: Entries
modelClass: Pensoft\Calendar\Models\Entry
list: $/pensoft/calendar/models/entry/columns.yaml
recordUrl: 'pensoft/calendar/entries/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
