list: $/pensoft/calendar/models/event/columns.yaml
modelClass: Pensoft\Calendar\Models\Event
title: Events
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/calendar/events/update/:id'
